# Generated by Django 4.2.28 on 2026-04-21 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.CharField(max_length=50)),
                ('tensao', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('marca_modelo', models.CharField(max_length=255)),
                ('numero_ranhuras', models.IntegerField()),
                ('numero_polos', models.IntegerField()),
                ('tipo_enrolamento', models.CharField(max_length=100)),
                ('espiras_por_bobina', models.IntegerField()),
                ('bitola_fio', models.CharField(max_length=50)),
                ('passo_bobina', models.CharField(max_length=50)),
                ('bobinas_por_fase', models.IntegerField()),
                ('tipo_ligacao', models.CharField(max_length=50)),
                ('esquema_fechamento', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_motor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
