# Generated by Django 4.2.28 on 2026-04-21 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_fichamotor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamotor',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fichamotor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
